name: Build and Sonar Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || echo "No tests found"

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.projectKey=GithubAction
            -Dsonar.projectName=GithubAction
            -Dsonar.host.url=http://<EC2_PUBLIC_IP>:9000
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
