name: Build and Sonar Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run tests
      - name: Run tests
        run: npm test || echo "No tests found"

      # 5. SonarQube Scan
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://16.16.96.22:9000
          SONAR_PROJECT_KEY: GithubAction
          SONAR_PROJECT_NAME: "GithubAction"
